export const pantalones = [
  {
    id: "jean-amc",
    nombre: "Jeans AMC",
    precio: 20,
    talla: "30",
    categoria: "pantalones",
    stock: 1,
    imagenes: [
      "/images/products/pantalon/Jeans-AMC-a.jpg",
      "/images/products/pantalon/Jeans-AMC-b.jpg",
      "/images/products/pantalon/Jeans-AMC-c.jpg",
      "/images/products/pantalon/Jeans-AMC-d.jpg",
      "/images/products/pantalon/Jeans-AMC-e.jpg",
    ],
  },
  {
    id: "jeans-jirish",
    nombre: "Jeans Jirish",
    precio: 28,
    talla: "32",
    categoria: "pantalones",
    stock: 1,
    imagenes: [
      "/images/products/pantalon/Jeans-Jirish-a.jpg",
      "/images/products/pantalon/Jeans-Jirish-b.jpg",
      "/images/products/pantalon/Jeans-Jirish-c.jpg",
      "/images/products/pantalon/Jeans-Jirish-d.jpg",
    ],
  },
  {
    id: "skiny-jeans",
    nombre: "Skiny Jeans",
    precio: 12,
    talla: "28",
    categoria: "pantalones",
    stock: 1,
    imagenes: [
      "/images/products/pantalon/Skiny-Jeans-a.jpg",
      "/images/products/pantalon/Skiny-Jeans-b.jpg",
      "/images/products/pantalon/Skiny-Jeans-c.jpg",
      "/images/products/pantalon/Skiny-Jeans-c.jpg",
      "/images/products/pantalon/Skiny-Jeans-d.jpg",
    ],
  },
  {
    id: "jeans-elle",
    nombre: "Jeans ELLE",
    precio: 33,
    talla: "30/32",
    categoria: "pantalones",
    stock: 1,
    imagenes: [
      "/images/products/pantalon/Jeans-ELLE-a.jpg",
      "/images/products/pantalon/Jeans-ELLE-b.jpg",
      "/images/products/pantalon/Jeans-ELLE-c.jpg",
      "/images/products/pantalon/Jeans-ELLE-d.jpg",
      "/images/products/pantalon/Jeans-ELLE-e.jpg",
      "/images/products/pantalon/Jeans-ELLE-f.jpg",
    ],
  },
];